### ISSUE TITLE
Erste Kalibrierung erfordert Kernel-Neustart und Arbeiten ohne Kalibrierung

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#1]
Für das erste Ticket leider etwas umfangreich (sorry), aber ich will es nicht zerstückeln, weil die Punkte wahrscheinlich ineinandergreifen.

1. Wenn die Kalibrierung ausgeführt werden muss und die cali.xlsx neu angelegt wird, kann diese ohne einen Kernel-Neustart nicht genutzt werden. Eine Reinitialisierung oder erstmalige Initialisierung von TG_IR Objekten oder das erneute Laden des Packages genügen nicht. Lässt sich das ändern? Wenn eher nicht, dann wäre die Info am Ende einer neuen Kalibrierung gut, dass der Kernel neu zu starten ist.

2. TG_IR.calibration() muss immer auf ein schon initialisiertes TG_IR Objekt angewendet werden? Wenn man das weiß ist es ok, aber nicht ganz intuitiv, da die Kalibrierung ja erstmal nichts mit diesem Objekt zu tun hat. Kann man die Kalibrierung auch separat durchführen? (nur wenn es nicht zu aufwendig ist) Die Information "No calibration data found. Supply mode='recalibrate'!" könnte dann nur etwas aussagekräftiger sein z.B.: "No calibration data found. To obtain quantitative IR data supply an 'Calibration' folder with cali.xlsx or initialize an arbitrary TG_IR object and further run TG_IR.calibrate(mode='recalibrate') on it".

3. Beim ersten Aufrud von TG_IR.calibrate kommt die kurze Info "Fill in 'Sample_list.txt' and rerun!", diese bitte auch ausführlicher, z.B.: "Sample_list.txt was created in 'Calibration' folder, please fill in calibration measurments and rerun this command."

4. Nach der Kalibrierung bitte noch eine Info einfügen, sinngemäß: "Calibration completed, data is stored in cali.xlsx in the 'Calibration' folder."

5. Ohne Kalibrierdaten enthält TG_IR.info den Eintrag 'mmol_c': 0 oder manchmal auch 'mmol_h': 0. Das ist ein überflüssiges Artefakt?

6. Wenn keine Kalibrierung hinterlegt ist (oder eine neue ohne Kernel-Neustart erstellt wurde) funktionieren bei der TG_IR.plot() Funktion keine Plots die IR-Daten verwenden. Auch keine bei denen die IR-Daten nicht quantitativ sein müssen!

7. In der früheren Version gab es beim Laden der Klasse die Info: "Calibration data loaded." Jetzt gibt es nur eine Info wenn keine Kalibrierung vorhanden ist (siehe 2.). Ist das gewollt oder unterwegs verloren gegangen? Die Info ist ganz nett, aber natürlich nicht zwingend erforderlich

Bei den nächsten Tickets halte ich mich auch an die Regel: Ein issue, ein Ticket ;-)
Danke, dass du das Projekt noch weiter mit begleitest!

**Comment by LeonSaal** [comment]
Kein Problem. Bin die Punkte durchgegangen und habe eine Rückfrage:
1. Wie meinst du das, dass cali.xlsx nicht genutzt werden kann? Kommen die Kalibrierdaten nicht im Objekt an oder in anderen Objekten? Das liegt wohl daran, dass das TG_IR Objekt einmal beim Laden den Packages mit der Kalibrierung initialisiert wird und diese 'globale' Größe n achträglich anscheinend nicht geändert werden kann.

Ansonsten wäre es gut, wenn du die anderen Punkte nach meinen Änderungen nochmal testest. 
Zu 2. sollte es jetzt möglich sein, tir. calibrate(mode=...) aufzurufen.

LG und gerne
