### ISSUE TITLE
.calibrate(mode='recalibrate') drei Kleinigkeiten

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#10]
1. Während der Kalibrierung werden die Namen der Messungen nacheinander ausgegeben, die gerade bearbeitet werden. Woher kommen diese Namen? Ich habe die von uns angepassten Freistzungsraten "_Langenau" für die Kalibrierung benutzt, während der Kalibrierung werden aber weiterhin die ursprünglichen Namen angezeigt - also wird nicht der Dateiname verwendet? Hat das einen besonderen Grund, in meinem Beispiel verwirrt es eher. 

2. bei plot = True erscheint nach jeder eingelesenen Messung: "Baseline correction: None" - Was hat das zu bedeuten? Es wurde eine Referenz in Sample_list.txt übergeben und die Freisetzungsraten sehen auch sehr gut aus, weshalb ich die Meldung nicht wirklich einordnen kann.

3. bei plot = True werden 4 Graphen gezeigt: DTG, TG, rel. TG, Freisetzungsraten. Ich denke 3 der Graphen in geänderter Reihenfolge würden genügen: rel. TG, DTG, Freisetzungsraten

**Comment by LeonSaal** [comment]
Zu 1.  habe ich eine ungute Vermutung. Kannst du mir die Ausagbe von folgendem Code schicken?

from TGA_FTIR_tools.input_output.general import find_files
from TGA_FTIR_tools.config import PATHS

file = 'XYZ_Langenau' # hier irgendeinen der Einträge aus der Sample_list.txt eintragen

print(find_files(file, '.txt', PATHS['dir_data']))
print('\n', find_files(file, '.csv', PATHS['dir_data']))

2 und 3 sind erledigt.

**Comment by danield5732** [comment]
Danke dir!!

Hier die Ausgabe der print-Befehle:

['C:/Users/ddittman/Desktop/2020-09-14_SPEKTRO_TGA-FTIR/Daniel\\Kalibrierung von Leon\\20-01-10_18358_12-26\\Freisetzungsraten_Langenau\\ls_6.6_18358_Langenau_012.txt']

 ['C:/Users/ddittman/Desktop/2020-09-14_SPEKTRO_TGA-FTIR/Daniel\\Kalibrierung von Leon\\20-01-10_18358_12-26\\Freisetzungsraten_Langenau\\ls_6.6_18358_Langenau_012_CO.CSV', 'C:/Users/ddittman/Desktop/2020-09-14_SPEKTRO_TGA-FTIR/Daniel\\Kalibrierung von Leon\\20-01-10_18358_12-26\\Freisetzungsraten_Langenau\\ls_6.6_18358_Langenau_012_CO2.CSV', 'C:/Users/ddittman/Desktop/2020-09-14_SPEKTRO_TGA-FTIR/Daniel\\Kalibrierung von Leon\\20-01-10_18358_12-26\\Freisetzungsraten_Langenau\\ls_6.6_18358_Langenau_012_H2O.CSV']

**Comment by LeonSaal** [comment]
Ah okay. Das Befürchtete ist nicht eingetreten!
Das Problem ist, dass als info['name'] nicht der Dateiname genommen wird, den wir nachträglich durchs Anhängen von '_Langenau' geändert haben, sondern der Name der Messung, der in den TGA-Daten im Dateikopf steht. Ist ja nicht die Regel, dass man die gleichen Messungen mit unterschiedlichen FTIR-Grenzen auswertet, oder?
Wenn es dir lieber ist, kann ich aber auch dafür Sorgen, dass der Dateiname ins Objekt übernommen wird.

**Comment by danield5732** [comment]
Mir ist letzteres tatsächlich lieber.
Das ist für die meisten Fälle intuitiver, da z.B. die Samplelog.xlsx ja auch über die Dateinamen anspricht.
Du hast mit der ursprünglichen Implementierung völlig recht, dass dies der tatsächliche Messungsname ist. Die Erfahrung sagt aber, dass hier gern auch Tippfehler entstehen, die im Nachhinein schneller über den Dateinamen geändert werden.
Wenn das Package also einheitlich immer mit den Dateinamen arbeiten würde wäre das ideal.
