### ISSUE TITLE
fitting: Gruppen im Ergebnis zusammenfassen

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#20]
In der Ausgabedatei (xlsx) des Fittingergebnisses sind alle gefitteten Peaks separat aufgelistet.
In der Fitting_parameters.xlsx legt man jedoch in der ersten Zeit auch Gruppen an.
Kannst du in einem separaten Tabellenblatt oder auch in 'summary' die Ergebnisse der Gruppen gleichen Namens schon addiert mit ausgeben lassen?

In dem Zusammenhang gleich noch zwei Punkte:

- Wir hatten einmal über Optionen gesprochen, dass die center-Temperatur der Gruppen von CO2 und CO auch gekoppelt werden kann, wie für die Carboxyle glaube ich ja auch schon gemacht wird. Dazu habe ich im Wiki jetzt nichts gelesen und in den Fitting_parameters.xlsx auch nichts gefunden. Hatten wir nicht überlegt, das über * oder sogar ** an den Gruppennamen individualisierbar auswählen zu können? Oder gibt es einen anderen Grund diese Funktionalität nicht mit aufzunehmen, an den ich mich gerade nicht mehr erinnere?

- Die Fitting-Ergebnisse werden auch in mmol_per_mg angegeben. Gehe ich richtig mit der Annahme, dass es sich hierbei auf die trockene Probenmasse bezieht? Das als Info im Wiki wäre noch super!

**Comment by LeonSaal** [comment]
+ Punkt 1: Die Funktionalität ist jetzt vorhanden, dafür gibt es ein neues Tabellenblatt in der _Fitting_parameter.xlsx_, 'link', bei Gruppen, die nicht nur ein Gas freisetzen, kann bei dem Gas, das vordefiniert werden soll (z.B. CO), in das Feld der Gruppe eine Kombination der Buchstaben 'c', 'w' und 'h' eingetragen werden. Damit werden bei:
    + 'c' der center vordefiniert
    + 'w' der HWHM vordefiniert
    + 'h' der height vordefiniert

    Mit `predef_tol=0.01` kann festgelegt werden, wie starr die Kopplung ist. 0.01 heißt das Endergebnis kann in  beide Richtungen um 1 %  vom Ausgangswert abweichen.

+ Punkt 2: Die Ergebnisse beziehen sich auf die 'reference_mass', die standardmäßig die Ausgangsmasse ist und nach erfolgreicher Korrektur die Trockenmasse.
