### ISSUE TITLE
Auflistung geladener Objekte vs. Samplelog

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#23]
ich denke es wäre praktisch, wenn man im Notebook eine Liste ausgeben lassen kann mit den Namen der geladenen Objekte. Vielleicht den Variablennamen des Objekts und dahinter der Name der geladenen Messung und wenn vorhanden der Alias.
Das würde bei längeren Listen und längerem Arbeiten im Notebook immer schnell wieder für Übersicht sorgen.

Lade ich die Messungen aus der Samplelog mit einer Schleife und lege diese in 'objs' ab, so kann man ja schon eine Liste durch den Aufruf .samplelog() erhalten. Da ich die Objekte aber noch mit dem Index in objs ansprechen muss, wäre es vielleicht ganz cool, wenn der Ausgabe von samplelog() die Indices als erste Spalte noch angefügt werden. So kann man in einer Liste aus 10 und mehr Messungen schnell sehen welche Messung nun hinter 'objs[5]' steckt.

Letzeres ist eine eigentlich ein Spezialfall vom ersten Absatz.
Wenn es zu aufwendig ist den ersten Absatz zu implementieren würden sicher auch die Indices aus dem 2. Absatz genügen, da dies der generelle Workflow sein wird.
Wenn du aber auch eine Lösung für den ersten Absatz findest, müsste beachtet werden, dass eben auch die geladenen Objekte die in 'objs' stecken so aufgelistet werden, dass man erkennen kann wie man sie anspricht. Das nur als Hinweis auf den Spezialfall, entscheide selbst, was du von dem Ticket hälst! ;-)

**Comment by LeonSaal** [comment]
Ich habe was Kleines gebastelt was du mal testen kannst. Dafür musst du aber alle Obejkte in einer Liste haben.

Also:
objs = [tir.TG_IR(name) for name in names] # fürs Initialisieren mehrerer Objekte
objs+=[tir.TG_IR(name)] # fürs Anhängen einzelner Objekte oder Listen von Objekten

Zum Ausgeben der Liste musst du tir.overview(objs) aufrufen, das sollte dir eine Tabelle mit Index, Name und Alias im Tabellenkopf ausgeben. Mit den Indizes kannst du dann wieder Subsets für weitere Auswertungen erstellen mit objs[x:y] (Slicing).
Falls das auch nicht gerade praktikabel ist, nur eine Liste mit allen Objekten zu haben, lass es mich wissen.

**Comment by danield5732** [comment]
Funktioniert wunderbar! Eine schöne Lösung.

Einzig ist der von mir gewünsche Index doppelt (aber besser als gar nicht vorhanden) ;-)

    index              name             alias
0       0  ls_6.6_18358_012  ls_6.6_18358_012
1       1  ls_6.6_18358_013  ls_6.6_18358_013
2       2  ls_6.6_18358_014  ls_6.6_18358_014
3       3  ls_6.6_18358_015  ls_6.6_18358_015
4       4  ls_6.6_18358_016  ls_6.6_18358_016
5       5  ls_6.6_18358_017  ls_6.6_18358_017
6       6  ls_6.6_18358_018  ls_6.6_18358_018
7       7  ls_6.6_18358_019  ls_6.6_18358_019
8       8  ls_6.6_18358_020  ls_6.6_18358_020
9       9  ls_6.6_18358_021  ls_6.6_18358_021
10     10  ls_6.6_18358_022  ls_6.6_18358_022
11     11  ls_6.6_18358_023  ls_6.6_18358_023
12     12    milc_17191_677    milc_17191_677
