### ISSUE TITLE
TG_IR.corr() how 'mass' und float funktionieren nicht

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#30]
Übergibt man dem how-Parameter 'mass' oder eine Zahl an die .corr Funktion erscheint folgende Fehlermeldung:

Failed to derive TG info.
Failed to derive IR info.

Die Messung ist eine neue CC Aktivkohle mit 75 mg Einwaage und recht großem Wasserpeak. Hier Das Ergebnis mit how = 'h2o':

![index](https://user-images.githubusercontent.com/19611569/101919863-5ecfab00-3bcb-11eb-9a76-c713036570a1.png)

**Comment by danield5732** [comment]
Mir fällt gerade auf, dass in der Abbildung TG und die Freisetzungsrate von Wasser gezeigt ist. Kannst du hier eine Legende einfügen, dass das klar erkenntlich ist?
Ich gehe davon aus, bei anderen 'how' wird dann an dieser Stelle das DTG-Signal oder garkeine zweite Kurve ausgegeben?

**Comment by LeonSaal** [comment]
Anstelle von how = 'mass', how = 'sample_mass' benutzen
