### ISSUE TITLE
TG_IR.plot('IR') unrund 

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#31]
#18 konnte ich nicht wieder öffnen, habe als Kommentar aber die neue Fehlermeldung hinterlassen

Hinzu kommt folgendes Verhalten, bzw. Auffälligkeiten:

legend = True/False (steht im Wiki widersprüchlich). Dieser Parameter funktioniert jedoch nur bei y_axis = 'rel'
In den default-Einstellungen mit y_axis = 'orig' passiert hier nichts. Es sieht immer so aus:
![index](https://user-images.githubusercontent.com/19611569/101948177-e4665180-3bf1-11eb-8728-9b29fe15a7ad.png)

auffällig ist hier noch, dass die beiden rechnten y-Achsen einen Lücke zum Plot aufweisen, kannst du diese entfernen?

**Comment by LeonSaal** [comment]
[#18 ](https://github.com/LeonSaal/TGA-FTIR-hyphenation-tool-kit/issues/18) habe ich (hoffentlich behoben).
Dass die Legende bei 'orig' nicht angezeigt wird war geplant, da die Linien durch die Achsen eindeutig zuzuordnen sind. Ich habe das jetzt aber entfernt, dass auch hier die Legende angezeigt wird.

Was meinst du mit widersprüchlich im Wiki?

**Comment by danield5732** [comment]
Im Wiki steht zuerst: legend = False.
In der Beschreibung der optionalen Parameter steht dann: Default True
