### ISSUE TITLE
dry_weight() noch existent?

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#33]
In einem alten Notebook habe ich den Befehl dry_weight(obj, plot=True) gefunden.
Vermutlich hat er den Plot ausgegeben, der von .corr ausgegeben werden kann.

Gibt es den Befehl noch irgendwo oder kann ich ihn vergessen?

**Comment by LeonSaal** [comment]
Den gibt es noch und er wird wie in #12 besprochen beim Initialisieren sowie Korrigieren ausgeführt. 
Nun kann er auch durch `obj.dry_weight()` angesteuert werden und hat dieselbe Funktionalität.
