### ISSUE TITLE
TG_IR.linreg und TG_IR.stats

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#34]
Diese Kalibrierungskenndaten sind für alle Objekte gleich aber werden über das Objekt abgerufen.
Kann man diese wie auch die calibrate() auf tir. umlegen?
Das erscheint mir erstmal intuitiver, oder gibt es einen Grund, weil die Objekte doch unterschiedliche Kalirbierungen hinterlegt haben können, diese separat im Objekt abzulegen?

**Comment by danield5732** [comment]
Zu diesen Kenndaten gibt es im Wiki auch noch den Verweis auf die Seite "Calibration" die es noch nicht gibt. (wäre schon schön, aber hat niedrigere Priorität auf dem Weg zum stable-release ;-)

Trotzdem wäre im Wiki noch die Info gut, in welchen Einheiten die Ausgegebenen Werte sind.

**Comment by LeonSaal** [comment]
linreg und stats sind jetzt auch in tir.linreg und tir.stats zu finden
