### ISSUE TITLE
überlagerte Plots

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#35]
In einem alten Notebook habe ich diese Zeile gefunden:
plots(*[objs[1],obj3],plot='TG',y_axis='rel',gas='h2o')

Das Resultet ist ein überlagerter TGA-Plot. Irgendwie dachte ich, dass das Package das gar nicht kann. Offensichtlich Fehlanzeige!

Aber wie greife ich aktuell auf die plots-Funktion zu? tir.plots() funktioniert nicht.

**Comment by LeonSaal** [comment]
Jetzt sollte es so klappen, wie du es probiert hast
