### ISSUE TITLE
es geht weiter... mass_step

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#36]
Wir haben auch mal 'mass_step' importiert. Ich sehe aber nicht mehr was das konnte, klingt aber vielversprechend. 
Gibt es das noch und wenn ja, wie funktioniert es? :-)
(wenn es sich hierbei um eine isolierte Funktion nur für die Kalibrierung handelt ist das wie immer auch ok)

In dem Zusammenhang gleich noch die Frage zum Auslesen gezielter Werte aus den Tabellen.
Mit dieser Syntax erhalte ich von allen geladenen Objekten die Masse bei 150 °C. 

`for obj in objs:`
`   print(obj.tga['sample_mass'][obj.tga['sample_temp']>=150].values[0])`

Fällt dir zufällig eine schöne "Template"-fähige Schreibweise ein mit der man diese und auch mehrere individuelle Temperaturen schnell auslesen kann?
Hinzu kommt das die Ausgabe des obigen Befehls beim Kopieren und Einfügen in Excel nicht glücklich macht.
Dazu kann ich mich aber auch nochmal umsehen. Das ist nur eine Basis-Funktion die alle anderen immer brauchen, daher würde ich diese gern maximal einfach und benutzerfreundlich ausführen wollen. (hätte ich dazu doch mal ein eigenes Ticket schreiben sollen..)

**Comment by LeonSaal** [comment]
Zu 1.: aktuell wird es nur für die Kalibrierung genutzt, aber ich hatte auch die Idee und Hoffnung, dass ich es als allgemeine Funktion mache.

Zu 2.: Wird gemacht! Da hatte ich zwischenzeitlich auch dran gedacht.

**Comment by LeonSaal** [comment]
Zu 2. habe ich eine kleine Methode fürs Objekt gebaut.

Heißt get_value(values, which='sample_mass', at='sample_temp')
values entweder int oder list als Wert/e der Vergleichsdaten, which Name der Spalte mit gewünschten Daten, at Name der Spalte der Vergleichsdaten.

Also aus deinem Beispiel: Masse bei 150°

obj.get_value(150)

**Comment by danield5732** [comment]
So einfach habe ich mir die Funktion nicht mal träumen lassen ;-D

Die Ausgabe ist schön, aber leider nicht schleifen-tauglich, dann erscheint leider keine Ausgabe. Hast du dafür noch eine Idee?

Ich könnte mir hier eine transponierte Ausgabe vorstellen. Je Objekt eine Zeile und hinterinander weg die ausgegebenen Werte.
(von mir aus muss das auch nicht in die Funktion implementiert werden, sondern nur in einer Schleifen laufen, auch ohne die angegebenen Temperaturen, da sie im Befehl direkt drüber stehen) Bsp.:
ls_6.6_18358_012: 1.07799 0.83828 0.16776
...

Aber du bist hier König ;-)

**Comment by LeonSaal** [comment]
Es erscheint keine Ausgabe, weil kein `print()` Befehl in der Funktion ist. Die Ausgabe im Notebook ist der Rückgabewert der Funktion.
Um die Rückgabe anzuzeigen musst du `print(obj.get_value(150))` nehmen.
Eine Schleife wie oben beschrieben könnte es so aussehen:

```
import pandas as pd
data=[]
temps=[150,160,500]
for obj in objs:
    data+=[obj.get_value(*temps).rename({'sample_mass':obj.info['alias']})]
out=pd.concat(data)
out
```
mit `out.to_excel('out.xlsx')` wird die Tabelle in `dir_home` abgelegt.
