### ISSUE TITLE
robustness

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#37]
Wie greife ich auf diese Funktion zu und wie funktioniert sie? ;-)
(gibt es auch im Wiki noch nicht)

Die einzige Zeile die ich dazu finden konnte ist diese veraltete:
`robustness(*TG_IR,reference,tol_c=30,tol_hwhm_0=95,T_max=None,save=True)`

**Comment by LeonSaal** [comment]
Sie lässt sich jetzt auch über tir. robustness(*TG_IR,reference,T_max=None,save=True,var_T=10,var_rel=0.3,ylim=[0,None],**kwargs):
aufrufen.
*TG_IR ist die Liste der Objekte die geprüft werden sollen, reference, T_max, save wie in .fit(). var_T und var_rel beschreiben die Abweichung der Start/Grenzwerte, die in Fitting_parameter.xlsx gegeben sind. 
Z.B. steht HWHM_max = 95, und var_T=10 guckt die Robustness auf 95 +-10. var_rel=0.3, HWHM_0=0.5 guckt die Robustness auf 0.5 +- 0.3

**Comment by danield5732** [comment]
Es gibt beim Ausführen leider noch Fehlermeldungen, wobei ich hoffe, dass ich die Funktion auch richtig bediene.
Vorher habe ich auch .fit auf die Objekte erfolgreich ausgeführt, wobei man das gar nicht braucht, oder?

Übergeb ich die ganze Liste objs via: **tir.robustness(objs,reference='saal2020b')**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-c644bff110d9> in <module>
----> 1 tir.robustness(objs,reference='saal2020b')

~\Downloads\TGA-FTIR-hyphenation-tool-kit-master\TGA_FTIR_tools\fitting\robustness.py in robustness(reference, T_max, save, var_T, var_rel, ylim, *TG_IR, **kwargs)
     11 
     12 def robustness(*TG_IR,reference,T_max=None,save=True,var_T=10,var_rel=0.3,ylim=[0,None],**kwargs):
---> 13     presets=get_presets(PATHS['dir_home'], reference, TG_IR[0].ir)
     14     params=['center_0','tol_c','hwhm_max','height_0','hwhm_0']
     15     results=dict()

AttributeError: 'list' object has no attribute 'ir'



Übergebe ich nur einen Eintrag scheint er schonmal anzufangen: **tir.robustness(objs[0],reference='saal2020b')**

Initial results:
Fitting according to 'saal2020b' in Fitting_parameters.xlsx is in progress ...

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-4cd59649b408> in <module>
----> 1 tir.robustness(objs[0],reference='saal2020b')

~\Downloads\TGA-FTIR-hyphenation-tool-kit-master\TGA_FTIR_tools\fitting\robustness.py in robustness(reference, T_max, save, var_T, var_rel, ylim, *TG_IR, **kwargs)
     19     #Init values
     20     print('Initial results:')
---> 21     res=fits(*TG_IR,reference=reference,save=False,T_max=T_max,presets=presets,**kwargs)
     22     for key in params:
     23         results[key+'_init']=res['mmol_per_mg'].drop(['CO2'],axis=1)

~\Downloads\TGA-FTIR-hyphenation-tool-kit-master\TGA_FTIR_tools\fitting\fitting.py in fits(reference, save, *TG_IR, **kwargs)
    181     for obj in TG_IR:
    182         #fitting of the sample and calculating the amount of functional groups
--> 183         peaks, sumsqerr=obj.fit(reference,**kwargs)
    184 
    185         #writing data to output DataFrames

~\Downloads\TGA-FTIR-hyphenation-tool-kit-master\TGA_FTIR_tools\classes.py in fit(self, reference, T_max, save, plot, **kwargs)
    189         temp.tga=temp.tga[temp.tga['sample_temp']<T_max]
    190         temp.ir=temp.ir[temp.ir['sample_temp']<T_max]
--> 191         peaks, sumsqerr=fit.fitting(temp,presets,plot=plot,**kwargs)
    192         print('Fitting finished! Plots and results are saved in \'{}\'.'.format(path))
    193 

TypeError: fitting() got multiple values for argument 'presets'

**Comment by LeonSaal** [comment]
robustness() ruft über fits() .fit() für jedes obj in objs auf, also .fit muss vorher nicht ausgeführt werden, außer man möchte ausführlichere Infos zum Fitting.

robustness() sollte jetzt über robustness(objs, ...) aufgerufen werden können, wobei type(objs)==list.
