### ISSUE TITLE
tir.calibrate(mode = 'recalibrate', method = ...) weird

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#38]
Ich habe ein Kalibriertnotebook geschrieben in dem neu kalibriert wird und danach die verwendeten Kalibrier-Messungen mittels 'IR_to_DTG' geplottet werden. Ich möchte mir hiermit nochmal die verschiedenen Kalibriermethoden (max, co_oxi, iter) ansehen und im Idealfall besser verstehen.

Ich habe nach Änderung der Methode den Kernel neu gestartet und immer das komplette Notebook durchlaufen lassen. In den 'IR_to_DTG' Plots habe ich aber so gut wie keine Unterschiede gesehen, obwohl die ausgegebenen Kalibrier-Parameter deutliche Unterschiede zeigen.

Dann habe ich das Notebook kopiert und für jede Methode ein eigenes erstellt, um es besser nebeneinander vergleichen zu können. Hier zeigen sich nun diese Effekte:

- im 'IR_to_DTG' Plot ist die Reihenfolge der Gase unterschiedlich, dadurch auch mit unterschiedlichen Farben. Für den angestrebten Vergleich ist das denkbar ungünstig, siehe diese Beispiel-Plots. Liegt das an der Methode oder noch an Problemen in .plot (#32 ?):
![index_iter](https://user-images.githubusercontent.com/19611569/101994647-3d9eb580-3cc4-11eb-84c6-74fe59735689.png)
![index_max](https://user-images.githubusercontent.com/19611569/101994650-40010f80-3cc4-11eb-95e0-58c8d2f34577.png)
Der erste Plot gefällt mir an dieser Stelle deutlich besser.

- ich werde immer verwirrter, jetzt habe ich den Kernel nochmal neu gestartet und die max-Methode ausgeführt und erhalte diesen Plot:
![index_max2](https://user-images.githubusercontent.com/19611569/101994729-d46b7200-3cc4-11eb-90a3-c5b8088404b7.png)
Dafür kenne ich jetzt meine (noch nicht vorhandene) Lieblingsreihenfolge der Gase: H2O, CO, CO2 - dann ist Wasser blau und die CO-Freisetzung aus Ca-oxalat ist im Plot unter der Kurve des CO2. 8-)

Mit dem nicht reproduzierbaren Verhalten fällt es schwer weiter zu testen. Liegt das überhaupt am Package oder am Jupyter Notebook, wenn ich mehrere Tabs mit verschiedenen Notebooks geöffnet habe? Eigentlich denke ich, dass die Kernel klar getrennt arbeiten, wobei ich mit allen Notebooks auf das selbe Arbeitsverzeichnis zugreife. Andererseits führe ich keine gleichzeitig aus. ich schicke dir das Beispielnotebook auch noch per Mail. 

Hoffe das Verhalten lässt sich noch korrigieren.

**Comment by LeonSaal** [comment]
Ich habe noch nicht ganz das Problem begriffen, abgesehen von der Reihenfolge im plot, die durch die Reihenfolge bei den Unterscheidlichen Methoden zustande kommt.
Im IR_to_DTG sollte sich die Reihenfolge erzwingen lassen, indem man gases=['h2o','co','co2'] als parameter übergibt.

**Comment by danield5732** [comment]
Danke für den Hinweis mit gases=
Ich teste spätestens am Mittwoch wieder, dann gebe ich dir nochmal Rückmeldung, vielleicht hat es sich auch durch die anderen Issues zu IR_to_DTG schon behoben.

**Comment by danield5732** [comment]
Ich kann es leider nicht richtig testen, da jetzt bei 'IR_to_DTG' diese Meldung kommt (was nicht stimmt) und nichts geplottet wird:
"Option unavailable without calibration!"

Alle anderen Plotting-Funktionen funktionieren.
