### ISSUE TITLE
IR Plots

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#44]
Ich eröffne mal einen neuen Issue, dass es nicht untergeht.

#18 (plotten einzelner Gase mit gases=) funktioniert noch nicht, siehe letzten Kommentar dort.

Eigentlich sollte dieses Problem auch mit #31 behoben worden sein. Siehe auch dort noch den letzten Kommentar bezüglich Default-Verhalten und Wiki-Eintrag.

Außerdem wirft das Plotten von 'IR', 'DIR' und 'cumsum' diese Warnung, wenn (default) eine Legende ausgegeben werden soll (mit legend=False, gibt es keine Warnung):
No handles with labels found to put in legend.

**Comment by danield5732** [comment]
Die Option y_axis='rel' für 'IR', 'DIR', 'cumsum' erzeugt jetzt leider einen leeren Plot und sagt zuvor noch: 
H2O and CO2 and CO not calibrated. Proceeding with .

**Comment by LeonSaal** [comment]
Ich habe dieses Verhalten nicht. Kann damit zusammen hängen, dass die Linreg nicht ordnungsgemäß geladen wurde.
