### ISSUE TITLE
robustness wirft nach fitting einen Fehler

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#49]
Das Fitting scheint erst noch ausgeführt zu werden, dann erscheint aber diese Ausgabe mit Fehlermeldung:

Initial results:
Fitting according to 'saal2020b' in Fitting_parameters.xlsx is in progress ...

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-5a80ec3e00a0> in <module>
----> 1 tir.robustness([objs[0]],reference='saal2020b')

~\Desktop\TGA-FTIR hyphenation tool kit\TGA-FTIR-hyphenation-tool-kit-4690a0941e1828591c9b62fd530d722cb868fe77\TGA_FTIR_tools\fitting\robustness.py in robustness(TG_IR, reference, T_max, save, var_T, var_rel, ylim, **kwargs)
     19     #Init values
     20     print('Initial results:')
---> 21     res=fits(TG_IR,reference=reference,plot=False, save=False, T_max=T_max, presets=presets, **kwargs)
     22     for key in params:
     23         results[key+'_init']=res['mmol_per_mg'].drop(['CO2'],axis=1)

~\Desktop\TGA-FTIR hyphenation tool kit\TGA-FTIR-hyphenation-tool-kit-4690a0941e1828591c9b62fd530d722cb868fe77\TGA_FTIR_tools\fitting\fitting.py in fits(TG_IR, reference, save, presets, **kwargs)
    191 
    192     # calculate statistical values
--> 193     dm=COUPLING.getfloat('mass_resolution')*1e-3
    194     for key in res:
    195         samples=list(set([get_label(re.search('(?<=_)\d{5}(?=_\d{2,3})',index).group()) for index in res[key].index]))

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

**Comment by danield5732** [comment]
Außerdem wird durch tir.robustness eine Fitting-Ergebnisdatei (..._orig.xlsx) im Arbeitsverzeichnis (dir_home) erzeugt.
Jede erneute Ausführung der robustness-Funktion erzeugt in dieser Datei neue Tabellenblätter mit angehängter laufender Nummer.

Ich vermute das Speichern oder zumindest der Speicherort ist hier nicht der richtige.

**Comment by LeonSaal** [comment]
Zum ersten Fehler:
in der settings.ini musst du unter coupling eine Zeile mit 
mass_resolution: 1 # in µg 
einfügen. Habe ich jetzt im Repo hinzugefügt
