### ISSUE TITLE
Einträge aus Samplelog.xlsx initialisieren

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#5]
In der früheren Version gab es die Funktion samplelog() über die man auf Samplelog.xlsx zugreifen konnte und so über einfache Schleifen eine Art "Stapelverarbeitung" der Einträge ausführen konnte.
Ich finde samplelog() jetzt nicht mehr, gibt es jetzt eine andere Möglichkeit alle Einträge aus Samplelog.xlsx auszuführen oder wo versteckt sich samplelog()? ;-)

**Comment by LeonSaal** [comment]
Sollte nun unter tga_ftir_tools.samplelog() aufrufbar sein.
