### ISSUE TITLE
tir.plots() wirft Fehlermeldung bei egal welchen 'plot'

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#52]
Nach der Beehebung von #51 funktioniert tir.plots() leider nicht mehr.
Egal ob plot='TG' oder plot='IR' es kommt zu dieser Fehlermeldung:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-f3b0db3b90b1> in <module>
----> 1 tir.plots(*objs,plot='TG')

TypeError: plots() got multiple values for argument 'plot'

Auch wenn man sinnlose Werte als 'plot' übergibt erscheint die selbe Fehlermeldung.

**Comment by LeonSaal** [comment]
Ich habe eine Änderung vorgenommen, dass statt *objs, nur noch objs übergeben werden muss.
