### ISSUE TITLE
tir.ribustness(): summary Tabellenblatt zu robustness.xlsx einfügen

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#54]
Wie schon in den Fitting xlsx Blättern, soll es auch in robustness.xlsx ein summary Tabellenblatt geben.
Darin würde ich mir für jede Probe diese Zeilen vorstellen (Spalten und Spaltenköpfe unverändert):

- mean (aus allen Mittelwerten der verschiedenen Tests bzw. Tabellenblättern zuvor)
- mean_stddev (Standardabweichung aller Mittelwerte)
- stddev (Standardabweichung aus allen Einzelergebnissen)
- min (aller Einzelergebnisse)
- max (aller Einzelergebnisse)

Wenn #20 umgesetzt wurde, wäre es auch cool in diesem summary-Tabellenblatt weitere Spalten entsprechend der Gruppen hinzuzufügen (als Gruppen-Summe aus CO- und CO2-Freisetzungsrate).

Frage: Die Zusammenfassung von Merhfachbestimmungen mit gleicher Probennummer wird nur von tir.robustness() vorgenommen, oder? An welcher Stelle ist die "Zusammensetzung" der Probennummer hart in den Code geschrieben?

**Comment by LeonSaal** [comment]
**Zur Frage:** _tir.fits()_ fasst ebenfalls Mehrfachbestimmungen zusammen. Die Zusammensetzung der Probennummer erfolgt nur in _fits()_, da _robustness()_ nur die Ergebnisse von _fits()_ sammelt und weiter auswertet. 

Um gleiche Proben zu finden werden die _'alias'_ der Proben auf gleiche Präfixe hin durchsucht. Dafür müssen die alias-Namen wie folgt aufgebaut sein:
**Präfix_X**, **Präfix_XY** oder **Präfix_XYZ**, wobei X, Y und Z Zahlen sind.
