### ISSUE TITLE
Priorisierung der Issues

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#56]
Ich versuche die offenen Issues gruppiert zu priorisieren:

**hoch**

- #30 TG_IR.corr() how 'mass' und float funktionieren nicht
- #50 tir.TG_IR(profile = 'Falk') ?
- #52 tir.plots() wirft Fehlermeldung bei egal welchen 'plot'
- #53 tir.robustness(): Anpassungen (siehe hierzu auch #54 unter "mittel", vermutlich gut zusammen zu bearbeiten)
- #29 Wiki-Eintrag zur correction
- Wiki-Doku generell
- siehe #38 weiter unten unter "überholt", das ist mir wichtig, aber vermutlich schon gefixt

**mittel**

- #36 es geht weiter... mass_step
- #20 fitting: Gruppen im Ergebnis zusammenfassen
- #54 tir.ribustness(): summary Tabellenblatt zu robustness.xlsx einfügen

**"special"**, da die Issues irgendwie zusammengehören

- #55 Feature request: Fitting_parameter.xlsx und settings.ini in Package integrieren
- #15 Befehl zum neu-Einlesen der settings.ini
- #16 Größe von Plots

**niedrig**

- #24 .corr() sagt "No CO2 baseline found."
- #19 matplotlib UserWarnung bei .plot('IR_to_DTG')
- #45 DTG-Einheit im TG-Plot
- #33 dry_weight() noch existent?

**überholt**

- #34 TG_IR.linreg und TG_IR.stats - ist nicht mehr aktuell, da nun doch jedes Objekt eine eigene und damit unterschiedliche Kalibrierung tragen kann. (das ist genial und erlaubt mit tir.plots() dann tolle vergleiche!)
- #38 tir.calibrate(mode = 'recalibrate', method = ...) weird - das hattest du dir bei unserem letzten Telefonat direkt notiert und ist damit wahrscheinlich schon erledigt, es ging um: 'gases' sollte nicht case-sensitive sein; 'IR_to_DTG' unterstützt 'gases' nicht; jede neue Kalibrierung rotiert die Reihenfolge der Gase in cali.xlsx

**Comment by LeonSaal** [comment]
Ein paar allgemeine Sachen vorweg:
+ Ich habe nun die Benennung der Gase auf Großbuchstaben umgestellt. Kleine werden abgesehen von der _Fitting_parameter.xlsx_ aber auch erkannt. Hat den Code an vielen Stellen vereinfacht, da ich bei print-Ausgaben die Klein- in Großbuchstaben umwandeln musste. Habe auch eingesehen, dass es formal nicht so schön ist, wenn chemische Elemente klein geschrieben werden.
+ Am Wiki habe ich noch nichts gemacht, das mache ich morgen parallel zu deinem Testen
