### ISSUE TITLE
Rotation, Änderung der Gase-Reihenfolge durch tir.calibrate()

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#58]
Wenn ich tir.calibrtate() mit mode = 'recalibrate' oder auch 'load' ausführe (danach die Objekte initialisiere und korrigiere), ändert sich nach wie vor die Reihenfolge der Gase, im Plot

for obj in objs:
    obj.plot('IR_to_DTG', gases = ['H2O','CO','CO2'])

Die Übergabde von gases = hat leider keinen Einfluss auf die Reihenfolge der Gase in der Legende, bzw. wie sie geplottet werden.

Bis jetzt dachte ich, dass sich hierbei auch in cali.xlsx die Reihenfolge der Zeilen von co, co2 und h2o oder Spalten h2o, co, co2 ändert. Dem ist aber nicht so (egal ob 'recalibrate' oder 'load'). 
Trotzdem verschiebt sich die Reihenfolge in der Plot-Ausgabe mit jedem "Kernel Restart & Run All".

Getestet habe ich das mit dem Notebook, welches ich dir letztens auch per Mail geschickt hatte.

Kannst du hier nochmal reinschauen, woran das liegen kann?

- Wenn es einfach umsetzbar ist, dass gases = die Reihenfolge festlegt bin ich schon wieder happy
- Alternativ, oder wenn das nicht geht, wäre eine reproduzierbare (nicht rotierende) Ausgabe der Plots wünschenswert

**Comment by LeonSaal** [comment]
Ich habe nicht rausgefunden woran es liegt, aber mit gases= lässt sich jetzt die Reihenfolge ändern
