### ISSUE TITLE
tir.plots(objs, plot = 'TG')

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#60]
geringe Priorität:

- Eine Überlagerung der DTG-Werte wird nicht mit angezeigt und plot = 'DTG' gibt es nicht. Kann man das unkompliziert nachrüsten?
- tir.plots(objs, plot = 'TG', y_axis = 'rel') schreibt als Achsenbeschriftung zwar "mass in %", beginnt aber bei 1 und nicht bei 100
- Außerdem liegt die 1 bei der Trockenmasse. Bei anderen Plots (obj.plot('TG')) liegen die 100 % bei der Start-Masse. Ist dieses Verhalten einstellbar, ich wüsste jetzt gleich gar nicht wo?

**Comment by LeonSaal** [comment]
+ DTG klappt jetzt als Parameter
+ ist behoben
+ es gibt nun `reference_mass=`, da kann man die Massen aus der `.info` eingeben, also` initial_mass`, `dry_mass `oder `final_mass`
