### ISSUE TITLE
fitting: Gruppen im Ergebnis zusammenfassen - TOLL :-D

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#61]
Deine Lösung (#20)  scheint super zu funktionieren, vielen Dank für dieses Feature!!!

- Wenn ich in Fitting_parameters.xlsx unter 'link' nichts eintrage erscheint während dem Fitting diese Info: "You cannnot predefine fitting parameters for all supplied gases!" Was möchte mir das genau sagen?
- Deine Methode hat für die Carboxyle ja schon derartige Vordefinitionen enthalten. Kannst du die in die Fitting_parameters.xlsx direkt mit reinschreiben? (Und weißt du noch welche der anderen Literatur-Methoden, das auch gemacht hat?)

**Comment by LeonSaal** [comment]
+ das wird jetzt nicht mehr angezeigt, das verhindert im Falle des Eintragens von links, dass man z.B. bei CO und CO2 Gruppen über das jeweils andere Gas vordefiniert
+ wird gemacht! Ich meine das waren fast alle die Figueiredo zitiert haben, bin mir aber nicht sicher.
