### ISSUE TITLE
.info - how und ref_mass während Initialisierung

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#64]
Es gibt die Messungen (von "Falk"), die nie .corr() erfahren, daher werden bereits alle Parameter für .info aus den Rohdaten bestimmt und von .corr() nur geupdated. 

Im Wiki steht noch nicht, dass daher bei der Objektinitialisierung die Parameter 'how' und 'ref_mass' übergeben werden können.
Man kann sogar schon **plot=True** übergeben und bekommt dann den TG-Plot (ohne DTG). In Bezug auf das was ich gleich weiter unten noch schreibe wäre es hier sinnvoll, den Plot zur Bestimmung der Trockenmasse zu zeigen, da man ohne .corr() diesen sonst nie zu Gesicht bekommen kann, oder?

Bei meinen Falk-Tests sieht es nun so aus als ob diese Parameter noch nicht so ganz das tun was ich (laut Wiki) erwarten würde.

how =
- 'h2o' - wird scheinbar ignoriert (es gibt keine H2O-Freisetzungsrate), es werden dann aber auch keine Massenstufen bestimmt (nicht schlimm)
- **'sample_mass'** - bestimmt den Trockenpunkt über das DTG-Signal (denke ich). Der Befehl hierfür hieß einmal nur 'mass' was ich jetzt beim Testen als klarer empfinde, da 'sample_mass' (auch weiter unten) sonst immer die Start-Masse der Messung meint, oder?
- float - funktioniert top
- None - funktioniert top

ref_mass =
- **'sample_mass'** - wird als 'reference_mass' in .info richtig eingetragen, aber die Massenstufen werden nicht bestimmt
- 'dry_mass' - funktioniert wie es soll, alle Massenstufen (absolut und relativ) werden in .info ausgegeben
- 'final_mass' - wird als 'reference_mass' in .info richtig eingetragen, aber die relativen Massenstufen werden über die trockene Probenmasse berechnet. (Den Masserückstand als Referenz zu verwenden braucht man wahrscheinlich eher selten, aber wäre von der Logik hier zu erwarten, oder wofür wird die Referenz sonst genutzt?)
- None - es wird in .info 'reference_mass': 'dry_mass' angegeben. Erwartet hätte ich, dass keine relativen Massenstufen ausgegeben werden. Man kann aber überlegen ob hier 'None' überhaupt sinnvoll ist? - denn eine Referenz braucht es doch irgendwo immer.

Die Optionen die ich als relevant ansehe und mich freuen würde, wenn du sie nochmal prüfen kannst habe ich **fett** dargestellt. Sonst weißt du vielleicht gar nicht was ich von dir will..

Vielleicht ist das Verhalten auch dadurch teils unerwartet, weil es bei der Initialisierung aufgerufen wird und nicht durch die Korrektur? .corr() habe ich nicht explizit darauf getestet. Wenn du sagst das wäre gut, dann mache ich das noch! :-)

Und noch was: 'how' ist bei der Initialisierung als auch bei der Korrektur noch kein aussagekräftiger Parameter. Kannst du den ohne Bedenken (bezüglich der Stabilität) in 'how_dry' umbenennen?

**Comment by LeonSaal** [comment]
`how=`
+ `h2o `oder `H2O` erzeugt bei mir immer die Massenstufen und auch im Code habe ich nicht gesehen was das verhindern sollte
+ `sample_mass `ist nun die Masse der Probe in Abhängigkeit von der Temperatur. Die Startmasse habe ich nach Absprache in `initial_mass` umbenannt. Hatte ich aber nicht auf dem Schirm, als ich es als mögliche `ref_mass` angeführt habe (siehe unten)
+ wurde in` how_dry` umbenannt

`ref_mass=`
+ `sample_mass` -> `initial_mass` (siehe oben)
+ `final_mass` funktioniert bei mir wie es soll (im plot wie in der `.info`)
+ None habe ich in `dry_mass` umbenannt, da das der Standard der Funktion ist
