### ISSUE TITLE
Beispiel für how und ref_mass

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#67]
Das Verhalten aus Issue #64 gibt es bei mir mit diesen Messungen und Zeilen:

[Samplelog.xlsx](https://github.com/LeonSaal/TGA-FTIR-hyphenation-tool-kit/files/5757052/Samplelog.xlsx)
[mk_200115_20005_01.txt](https://github.com/LeonSaal/TGA-FTIR-hyphenation-tool-kit/files/5757059/mk_200115_20005_01.txt)
[mk_200115_20006_01.txt](https://github.com/LeonSaal/TGA-FTIR-hyphenation-tool-kit/files/5757060/mk_200115_20006_01.txt)
[mk_200115_20007_01.txt](https://github.com/LeonSaal/TGA-FTIR-hyphenation-tool-kit/files/5757062/mk_200115_20007_01.txt)

objs=[tir.TG_IR(name, profile = 'Falk', how = None, ref_mass = 'sample_mass') for name in tir.samplelog().index]

objs[0].info

sieht dann so aus:

{'name': 'mk_200115_20005_01',
 'date': '15.01.20',
 'time': '22:12:42',
 'method': '2=25<600(30N2)5=600(N2)/10_Alox150_ak',
 'initial_mass': 0.139,
 'reference_mass': 'initial_mass',
 'background_delay': 2,
 'method_gases': ['30N2', 'N2'],
 'switch_temp': [600, 600],
 'alias': 'PLA_05'}

**Comment by LeonSaal** [comment]
ref_mass versteht 'sample_mass' nicht. es gibt 'initial_mass', 'dry_mass' und 'final_mass'
