### ISSUE TITLE
Fitting-Ergebnis mit und ohne "link"

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#68]
Wenn in den Fitting_parameters.xlsx unter "link" in der Spalte "anhydride" von "CO" etwas eingetragen ist (z.B. "hw"), dann bedeutet, dies, dass die Parameter h und w für den Fit von CO fest vorgegeben werden, aus dem Fitergebnis von CO2.
Das Fitergebnis von CO2 sollte also nicht von diesen Einstellungen abhängig sein, da CO2 und CO nicht gemeinsam optimiert werd. (was so eine Abhängigkeit ja auch bedeuten könnte) - Weil die Plots aber deutlich zeitversetzt ausgegeben werden, bin ich mir hier eigentlich sicher. Oder verstehe ich schon etwas falsch?

Jetzt das unerwarete Verhalten: das Fit-Ergebnis von CO2 (welches als erstes durchgeführt wird) sieht hier unterschiedlich aus.
Kannst du das erklären?

Mit "hw" für die CO-anhydride:
![mit](https://user-images.githubusercontent.com/19611569/103414428-3a3d7200-4b7e-11eb-96c3-fbe77cae8ee2.png)

Ohne "hw" für die CO-anhydride:
![ohne](https://user-images.githubusercontent.com/19611569/103414431-3f9abc80-4b7e-11eb-905d-0cc0d528316e.png)

**Comment by LeonSaal** [comment]
+ Das Verfahren verstehst du richtig, das fitten erfolgt nacheinander und nur CO ist dann abh. von CO2
+ Dein Problem ist wirklich komisch. Ich habe es mal bei mir probiert und da bekomme ich das gleiche Ergebnis für CO2.
Vielleicht hat sich das Problem durch mein Bearbeiten anderer Fehler gelöst.
