### ISSUE TITLE
Plot zur Bestimmung der Trockenmasse

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#69]
Egal ob während der Initialisierung oder während der Korrektur, mit plot=True werden jetzt je Messung 5 Plots ausgegeben. Der letzte ist der für die Bestimmung der Trockenmasse.
Vor diesem Plot erscheint die Meldung:

Failed to derive TG info. 
Failed to derive IR info.

Der Plot der gezeigt wird ist dann recht leer (keine Überschrift und Achsenbeschriftungen wie in den anderen Plots, und auch keine eingetragene Trockenpunkt-Bestimmung):
![index](https://user-images.githubusercontent.com/19611569/103415053-d2d4f180-4b80-11eb-918f-43651c9d81c4.png)

Hast du eine Idee woran das liegen kann?

**Comment by LeonSaal** [comment]
Kannst du den Aufruf der Funktionen schicken?
Ohne weitere Infos habe ich keine Idee woran es liegen kann.

**Comment by danield5732** [comment]
Der Plot wird so aus den Default-Parametern erzeugt. Also z.B.

objs[0].corr(plot=True)

oder auch

tir.calibrate(mode='recalibrate', plot=True)
