### ISSUE TITLE
Fragen zur Ausgabe von tir.fits()

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#71]
Zur summary.xlsx von tir.fits() kurze Fragen:

- Es gibt die Spalte "run" in der i.d.R. eine 0 steht. Was steckt dahinter oder soll ich sie einfach ignorieren?
- Es gibt die Zeilen "stddev", im Tabellenblatt "mmol_per_mg" heißt sie nur "dev". Ich meine in diese Abweichung bzw. Unsicherheit fließt auch die Bestimmungsgrenze aus der Kalibrierung mit ein. Kannst du hier im Wiki bitte nochmal zusammenfassen welche Werte hier wie verrechnet werden?
- Im selben Tabelleblatt gibt es in den hinteren Spalten ..._sum und ..._mean, was fließt dann hier in die Berechnung der "dev"-Zeile ein? (auch ins Wiki bitte).

Das solls gewesen sein. :-)

**Comment by danield5732** [comment]
🥇

**Comment by LeonSaal** [comment]
+ _run_ kann ignoriert werden. Das ist die laufende Zahl bei Mehrfachbestimmungen bzw. die Messnummer
+ genau, da wollte ich eine Unterscheidung zw. stddev und dev machen, da sie anders berechnet werden
+ für sum und mean ist es aktuell nur die stddev, weil ich in dem Augenblick nicht nochmal die Fehlerfortpflanzung einbauen wollte. Ist das okay? Kommt so oder so ins Wiki
