### ISSUE TITLE
Fitting und Robustness

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#72]
1. Es ist durchgelaufen!
2. Eine tolle Idee die erwartete Zeit am Anfang auszugeben! (bei mir war er dann sogar etwas schneller fertig) 👍 
3. trotzdem noch ein paar gesammelte Punkte

- Was ich in #68 geschrieben und an Abbildungen gepostet habe liegt nicht an den Einträgen in "link", sondern am Ausführen von tir.fits() oder TG_IR.fit(). Kann es sein, dass bei tir.fits() vielleicht nur weniger Iterationen für die Deconvolution durchlaufen? Denn dort ist der Fit optisch deutlich schlechter und man sieht es auch an den SQERR Werten. Das wiederum schlägt auch auf tir.robustness() durch, weil hier wohl tir.fits() verwendet wird. Ich habe die Ergebnis-Ausgaben von beiden verglichen, was die Behauptung bestätigt. ... kannst du hier nochmal ...?
- Am Ende der Ausgabe von tir.fits() werden jetzt sehr lange Tabellen ausgegeben (wahrscheinlich summary.xlsx). Kannst du die wieder wegnehmen und wie bei TG_IR.fit() nur den Info-Text ausgeben wo die Ergebnisse gespeichert wurden?
- Mit einem der letzten Updates hattest du die Gruppenzusammenfassungsspalten _mean und _sum eingeführt (#20). Dazu eine Frage: gibt es einen Grund den Mittelwert zu bilden, wenn es um die freigesetzte Menge SOG gleicher Gruppe geht? Mir erscheint hier die Summe allein sinnvoll. Könntest du ggf. die _mean Spalten weglassen? (wenn du dabei keine Sorge bezüglich der Stabilität hast!)
- Zu diesen neuen Spalten werden nur Gruppen herangezogen, die es auch mehrmals gibt. Dadurch fallen die Phenole und Pyrone etwas unter den Tisch. Auch wenn es hier nichts zu summieren gibt, kann man quasi für jede Gruppe die Summen-Spalte ausgeben lassen?
- Diese neuen Spalten werden jetzt auch auf der x-Achse in den Plots von tir.robustness() mit ausgegeben. Könntest du diese in den Plots einfach weglassen (ansonsten in einen separaten Plot verschieben)? Es ergeben sich nämlich zwei ungünstige Fälle: (i) durch die Summen-Spalte wird die y-Achse größer skaliert und und für die Unterschiede in den anderen Werten hat man nicht mehr so viel Platz, (ii) durch die unterschiedliche Berechnungsgrundlage von dev (mit und ohne Fehlerfortpflanzung als stddev #71) ergeben sich in den Plots nicht nachvollziehbare Unterschiede in den Fehlerbalken.
- Im Plot "center" (und auch in robustness.xlsx) ergeben sich durch minus und plus keine anderen Werte. Das war beim letzten lauffähigen tir.robustness() Test noch nicht so. Ich vermute hier hat sich ein Fehler eingeschlichen.

Der erste und die beiden letzten Punkte wären von meiner Seite leider noch "hoch" zu priorisieren.

**Comment by LeonSaal** [comment]
Freut mich erstmal, dass es auch bei dir durchgelaufen ist und auch, dass dir meine kleinen Gimmicks auffallen :)
Zu den Punkten:
+ Zu #68 habe ich das Problem gefunden. Kann es sein, dass vor der PS WP in `fits()` eine andere Kohle gefittet wurde, die weniger CO2 freisetzt? Die fit-Grenzen wurden bislang nur einmal eingelesen und die maximale height orientierte sich am IR-Signal der ersten Messung in `fits()`. Jetzt wird es für jede separat bestimmt, wie es sein sollte.
+ Der Infotext ist eingefügt. Die Ausgabe der summary kommt durch Jupyter zustande. Der Rückgabewert der Funktion am Ende eines Blocks die ohne Zuweisung aufgerufen wird, wird automatisch ausgegeben. Das kann auf zwei Wege verhindert werden:
     + `x=tir.fits()` (Zuweisung)
     + `tir.fits();` (Unterdrücken der Ausgabe durch ein Semikolon)
+ Die _mean Spalten habe ich wegen der Anhydride eingefügt. Die setzen ja pro mol Gruppe zwei mol Gase frei, also ist die Anzahl der Gruppen die Summe der Gase durch zwei aka der Mittelwert. Wenn du das lieber separat berechnest, kann ich das auch raus lassen
+ Das ist machbar, alternativ könnte ich auch die Spalten sortieren lassen, dass z.B. Carboxlye 1, 2, _sum, _mean da steht und dann die nächste Gruppe kommt
+ Für die plots in `robustness()` lasse ich '_mean' und '_sum' weg. Die Werte finden sich ja trotzdem in der Excel-Tabelle
+ Hat etwas gedauert, aber ich habe das Problem gelöst, auch wenn ich nicht ganz verstehe, wie der Fehler zustande kam
