### ISSUE TITLE
Laden des Packages legt working directory auf C:\\Calibration

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#74]
Hallo,

wenn ich das Package erstmalig lade kommen Infos, dass settings.ini und die anderen beiden .xlsx Konfigurationsdateien herungeladen und im Installationspfad des Packages abgelegt werden.
Was nicht kommt ist die Frage nach dem Pfad zu den Daten und auch keine Info welches home Verzeichnis automatisch festgelegt wurde.

Ruft man .samplelog() auf, wird unter C:\\Calibration eine leere Samplelog.xlsx angelegt. In diesem Pfad findet sich aber keine weiteren Dateien, wie z.B. settings.ini

Ich vermute, hier ist noch ein Käfer unterwegs.
Denn so bin ich aktuell nicht in der Lage das Home-Verzeichnis zu ändern oder mitzuteilen wo sich die zu analysierenden Daten befinden.

Danke für Hilfe und eine Lösung!

**Comment by LeonSaal** [comment]
Hallo,

das ist sehr ärgerlich. Es lag wohl daran, dass ich die Pfade komplett neu strukturiert habe. Weil ich die settings.ini vor dem Testen nicht gelöscht hatte, ist mir der Fehler nicht begegnet...
Hast du versucht, die settings.ini manuell zu kopieren und modifizieren? Das hätte funktionieren sollen.

Ich hoffe es klappt jetzt!

**Comment by danield5732** [comment]
bei aktuellen Test funktioniert jetzt alles und beim ersten Laden des packages gibt es auch klar Infos was wo liegt, bzw. wo Fitting_parameters und die setting.ini abgelegt werden.
Top!
