### ISSUE TITLE
wl.corr(how_dry=...) hat schwierigkeiten bei gemischten Datensätzen

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#75]
"gemischte Datensätze" meint, dass in der Worklist Objekte mit und ohne FTIR-Daten vorhanden sind.

wl.corr(), ohne die Angabe einer expliziten how_dry Anweisung, läuft problemlos durch.
Gibt man jedoch 'H2O', 'sample_mass' oder eine Zahl vor, so bricht die Korrektur beim Wechsel zum nächsten Objekten ohne FTIR-Daten ab.
Wenn ich es aus der dry_weight() Abbildung richtig sehe, wird die Angabe von how_dry (z.B. 100) anscheinend auch ignoriert und durchgeführt als wäre 'H2O' vorgegeben.

Das kann ich nicht direkt nachvollziehen, scheint aber reproduzierbar.

**Comment by LeonSaal** [comment]
Sollte mit Fixes für #78 und #79 behoben worden sein.
