### ISSUE TITLE
angepasste Bestimmung der Trockenmasse funktioniert nicht und verursacht Folgefehler

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#78]
.corr() als auch in .dry_weight() bestimmen zusätzlich den Trockenschritt der Probe.
Automatisch erfolgt dies über das H2O Signal oder den ersten DTG-Peak. 
Gibt es beides nicht, kann mit dem Parameter how_dry der Prozess zur Festlegung des Trockenschritts spezifiziert werden (z.B. durch Vorgabe einer konkreten Temperatur).

how_dry kann zwar an .corr() übergeben werden, wird aber ignoriert. Siehe dazu auch #75 

Wird zur Korrektur des automatisch falsch ermittelten Trockenschritts .dry_weight(how_dry=...) durchgeführt so wird der Trockenschritt und alle Infos in .info() korrekt neu bestimmt.
Es kommt aber zu einem Folgefehler bei der Berechnung der rel_ML_... Stufen, die aus step_temp und mass_steps ausgelesen werden.
Auch wenn dry_mass, dry_temp und ML... richtig aktualisiert werden, wird rel_ML... weiterhin mit dem alten dry_mass Wert berechnet und erzeugt so in der samplelog nicht mehr nachvollziehbare Werte.
(nicht geprüft: Eventuell wird dry_time nicht aktualisiert und darüber dry_mass in der Berechnung verwendet?)

Durch diese Verquickung gibt es aktuell keine Möglichkeit Proben auszuwerten, bei denen die automatische Trockenschritt-Bestimmung nicht die richtigen Ergebnisse liefert.

**Comment by danield5732** [comment]
Sind Freisetzungsraten vorhanden kommt es bei Verwendung von 'how_dry' zur Fehlermeldung, dass corr_FTIR() einen unerwarteten Parameter 'how_dry' bekommen hat.

**Comment by danield5732** [comment]
`[ INFO  ] sample.corr: ".info" of dd_221028_Lewatit-TP-108_01 was updated. To store these in Samplelog.xlsx run ".save()"
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 1
----> 1 wl_IX.corr(how_dry = 150, plot=True)

File [c:\Users\dittmann\Desktop\UBA-cloud\TGA-FTIR\TGA-FTIR-hyphenation-tool-kit_CLONE_4_testing\TGA_FTIR_tools\classes\worklist.py:110](file:///C:/Users/dittmann/Desktop/UBA-cloud/TGA-FTIR/TGA-FTIR-hyphenation-tool-kit_CLONE_4_testing/TGA_FTIR_tools/classes/worklist.py:110), in Worklist.corr(self, references, plot, **kwargs)
    107     references = [None for _ in self.samples]
    109 for sample, baseline in zip(self.samples, references):
--> 110     sample.corr(baseline, plot=plot, **kwargs)

File [c:\Users\dittmann\Desktop\UBA-cloud\TGA-FTIR\TGA-FTIR-hyphenation-tool-kit_CLONE_4_testing\TGA_FTIR_tools\classes\sample.py:222](file:///C:/Users/dittmann/Desktop/UBA-cloud/TGA-FTIR/TGA-FTIR-hyphenation-tool-kit_CLONE_4_testing/TGA_FTIR_tools/classes/sample.py:222), in Sample.corr(self, reference, plot, update, **kwargs)
    219 if self.ir is not None:
    220     try:
    221         self.ir.update(
--> 222             corrections.corr_FTIR(
    223                 self.raw, self.baseline, plot=plot["ir"], **kwargs
    224             )
    225         )
    226     except PermissionError:
    227         logger.error("Failed to correct IR data.")

TypeError: corr_FTIR() got an unexpected keyword argument 'how_dry'`

**Comment by LeonSaal** [comment]
Probleme sollten behoben sein, da gab es ein paar Referenzierungsfehler. Danke für die aufmerksame Benutzung/Testung! 👍 

Um `how_dry` an `Sample.corr()` übergeben zu können, musst du jetzt das Argument als `dict` übergeben, damit es bei der richtigen Funktion ankommt:
```
Sample.corr(... , dry_args={"how_dry": ...}
```
oder für Argumente der IR-Korrektur:
```
Sample.corr(... , ir_args={... : ...}
```
