### ISSUE TITLE
dry_temp und step_temp nicht kongruent

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#79]
Die Temperatur in dry_temp weicht um ca. 3 K von der in step_temp aufgeführten Temperatur ab.

Bei der Prozedur von #78 werden beide Werte aktualisiert, die geringe Abweichung bleibt jedoch.
(Vermutlich ist das eine die Methoden- und das andere die Proben-Temperatur?)

**Comment by LeonSaal** [comment]
Problem sollte behoben sein. Guter Riecher mit Methoden- und Probentemperatur! 👍  Daher stammte die Diskrepanz.
