### ISSUE TITLE
Initialisieren einer Probe übernimmt nicht den alias-Eintrag der Samplelog

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#80]
name wird einfach in alias kopiert.

**Comment by danield5732** [comment]
merkwürdig, auch nach .save() erscheint der ursprüngliche alias aber in der Legende von plots()

**Comment by LeonSaal** [comment]
Was wolltest du denn erreichen/ was hat nicht geklappt?
Dass der `.name` in `.alias` kopiert wird ist so gewollt, da die plot-Funktionen nur auf das `.alias`-Attribut zugreifen für die Legende.

**Comment by danield5732** [comment]
Danke für die Bearbeitung der ganzen Tickets!
Ich war nicht sonderlich ausführlich, weil es nur schnelle Notizen für mich waren.

Gemeint ist hier, dass .name immer in .alias kopiert wird und so ggf. den Alias-Eintrag der Samplelog.xlsx überschreibt.
Beim ersten mal ausführen eines Notebooks ist das (warum auch immer) unkritisch weil in den Legenden der plots der Alias noch verwendet wird. Wurde dieser aber dann in Samplelog.xlsx überschrieben steht dann in den Legenden wieder nur der Name der Messdatei.
.name sollte also nur in .alias kopiert werden wenn dort noch nichts drin steht.

**Comment by danield5732** [comment]
Siehe das aktuelle Notebook Auswertung_neu2.ipynb - dort tritt der Fehler noch auf.

- in der samplelog() ist die 'alias' Spalte noch richtig gefüllt
- nach dem Initialisieren der Worklist steht in der .info unter 'alias' bereits der Text aus 'name'
- ärgerlich wird es wenn man dann die Samplelog.xlsx durch Speichern aktualisiert und die Alias so verloren gehen
- für mich unerklärlich wird der Alias aber im weiteren Verlauf der Notebooks in den Plots angezeigt, obwohl er gar nicht mehr beim Objekt hinterlegt ist.
