### ISSUE TITLE
Initialisierung des Packages

### ISSUE THREAD

**Issue by danield5732** [LeonSaal/TGA-FTIR-hyphenation-tool-kit#82]
Fitting_Parameters.xlsx landet irgendwo, wird zwar beim allersten Laden angezeigt, aber dann nicht wieder. (setting.ini wird netterweise zusätzlich in lokales Verzeichnis übernommen.)

**Comment by LeonSaal** [comment]
Den Ort der Datei kannst du dir mit:
```
import TGA_FTIR_tools
TGA_FTIR_tools.fit_references()
```
ausgeben lassen. 
Ansonsten sollte die Datei beim ersten "fit-Versuch", also bei Bedarf ins lokale Verzeichnis kopiert werden.
